### ISSUE TITLE
Testing the program on example graph in paper

### ISSUE THREAD

**Issue by sgyzetrov** [fgullo/uncertaincores#1]
Hi,

I tried to run `KEtaCores_DynamicProgramming_BigDecimals_IncrementalInitialEtaDegrees` on the sample small graph in the paper (Figure 1).

Data:
```
0	1	0.9
1	2	0.5
1	3	0.2
2	3	0.6
2	4	0.6
2	5	0.4
3	4	0.1
3	5	0.8
3	6	0.1
4	5	0.5
5	6	0.5
```

Code:
```java
java KEtaCores_DynamicProgramming_BigDecimals_IncrementalInitialEtaDegrees test.txt 0.04
```

And I cannot seem to get the paper's result where vertices 3, 4, 5 and 6 have core number 3.

Program output:
```
0	1
1	2
2	2
3	2
4	2
5	2
6	2
```

Any idea why? Thanks!

Best,

**Comment by fgullo** [comment]
Hi,

unfortunately, there is a mistake in the paper: \eta should be 0.03 (and not 0.04) in the example.

To see why, please note that the only way for node 5 in the paper (= node 4 in your test dataset) to have \eta-degree equal to 3 (and, as such, have chance of being part of a core of order 3) is for \eta <= 0.03.
In fact, node 5 has 3 adjacent edges, with probabilities 0.6, 0.1, and 0.5, respectively. So, the probability that all such edges exist is 0.6 x 0.1 x 0.5 = 0.03. 

Thanks for noticing this.

Best,
Francesco

**Comment by sgyzetrov** [comment]
Thanks so much for the reply! - 

This might seem like a very dumb question but when we calculate the coreness in Figure 1 **by hand**, I imagine the procedure would be Algorithm 1, that is: first start with node1 in Figure1 (and it is obvious that if \eta=0.03, node1 is in core1 since it only has one edge and Pr[deg(node1)>=1]=0.9 > 0.03), then we **remove** node1 and update the degree of node2, then we continue to do node2 and node7 and we no longer consider graph G but rather a sub-graph H containing only node2-7 right? 

Best,

**Comment by fgullo** [comment]
Yes, exactly!
